services:
  - docker
branches:
  only:
    - master
install:
  - docker build --target test --tag todo-app:test .
script:
  - docker run todo-app:test tests
  - docker run -e DB_CONNECTION_STRING todo-app:test tests_e2e
after_success:
  - echo $DOCKER_PASSWORD | docker login --username chengjoanna1729 --password-stdin
  - docker pull chengjoanna1729/todo-app
  - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from chengjoanna1729/todo-app --target production --tag chengjoanna1729/todo-app:latest .
  - docker tag chengjoanna1729/todo-app:latest chengjoanna1729/todo-app:$TRAVIS_COMMIT
  - docker push chengjoanna1729/todo-app:$TRAVIS_COMMIT
before_deploy:
  - docker push chengjoanna1729/todo-app:latest
deploy:
  provider: script
  script: curl -dH -X POST "$WEBHOOK"
  on:
    branch: master
env:
  global:
  - secure: F2xfgjhsGpnzRHQIAkakCh7J9/PZTZV9AKhLDuPURmZlSBdZ+iR2wvyWHQ97Q9wO/UMmUxuJT/b4k4LkuHEZLGSKl6pzRgg+2Prhz/MTDvTYJYwIAdfSqws0U6TqDVVLnLNNzy3az/zFhDEfztHzbcy4dzPCfGtcA46ziZtbyl28/yzjR/wQQCrl4xecfHjae5R9FF7CF2A8e9kAspjurW/s+0erXaCD49BVUd4AxT1yswhshI2MPHE4+NNPn+s9oskjUXaUmPEgg3I9vGtS5rASoLozp57Leuola1rJRZxd0TVs5nOX3Jv+5EaDECJzjNq6PcXC/JbcmBt4wt3r0UmJrOs3t9VHiPhd4/kPIHFq7rNgPpvKhwBN/aqAaTC9Jh/58HZD99LtNXO9EJR6yHtlFI8AdbAuNsj6lFGtOGDv6dQyMYYigdMKoaK3zIh6Wm9L1YFboYbTcvP2Fc0HvoH9YeLQ63wqd5VuHT92gOgNSu6/biTczdzMk8qpDcgTH2db34dwCqxIf97rNOE75VQw7EBuU2gsUPbU2TNRHml1ExmFDGl9tAlxddFDm0FIsDzWbyA6BCoK4M+f5MF/Bgm6+YJyQZr0AZrKTcpvHHs6n+FLjlf6W7Mh+GBnY7rjWU2LxF9ibepEGE+PFnaNb4ILJXg7CZmcN0nqt8z0DwE=
  - COLLECTION_NAME=todos
  - secure: SHQLapApBkDsp91QFSR/ekDJfjlorx9vGxv9sJ8192/ktgiPS7IoR+3fm/klPSFzlA6WFM58TNMLOeGOQDOxGvqf8rlUlZrjQ7GXRaQpAd+H7A9QyPAFcqP0Rxm2cE1k9Q2kUoB6r7jpuGx5YnkUNi4vhEK3GAdi4Zq59lTr6jeLk8avsde0mqhbQdfpQnR08lzD8XjXbhCFJmnRx1tUBc6lxJyApZho30RYMWY3GMvl82TNRuxFby7x+g86UgFG19c1o/nLLje99tIvh5tjYvoPRmkl7iPADlKYj29K9TvveYdnWdb3LPOk/J3SnXSjREAw19Zq+zi1I6abOtxvQg5hPSfoILft72UvBmalWZnKlTHgEI8eJP5lGHBdthJXVMB3bhv/mCXlSXWztrAM5C0Tg0MTAgqSLBqEIXRsAhN9g/XTfqpYhYak1UhaTr7pt4JYxCAZKF7JkYl1qnD2kyaexUw34Tbw9WxgOXhG7zvN8lmP2XuCSvy+2zjzpPwFo0+Vhd2n8BSvHbeSj+h9E2fzkB6y5iKWlKOItHIoGxTFbWwbr7za0qFskPZJkxsQl0HID8pj12ENmsz+dJxe36kNzoiN0urjI+SoAzmNmMbn80cs2+Op1Pj30sWiM7PTLBXxx4IUIfWRMgESJ6c3B8IVHksp0cnaPoFcNWNeoN0=
  - secure: D3Awb1Z5iTcu0hQB0bdsZrsPYybliOIXD4XD2N3g2o9uDgKYW8eHOrhYfL3YWBuxzn+kOTsGR73epMVoyt/EdDKZBDlVh/cf0A1LhWTAYevEwfMi6yC29V1rKK69EgK3XxmCakLIJZ4e6tVSZAhyVpTknINXOVmcHDr25oNDOAfg9ct8sqbPVJ7+VMj4jC0BOo01HxMLQlZYYmeVMrLdOXhJ0CnkuS4dVgtUwECdK8VsNgae6Gevj8SePKLOnryJL121KOUw8xpic4nLuG/nq5nhie03zRjryszixqtNq3gPqniv22RsK3ZFO7euK+nOiXE0EI04d8kjFbS3dz7lEBV085bpDTyjWIhUSH13jJlEz/RgtQgeu3o6s5zyJ9y1WIEVcGRJ8LIEDdnl3lC/HFOks8Ui/eVDy83qYMJukDrMqFnHxkqgCkIa3yCywToWPn+5WVQKAe4TTp+S+TNp+5bGIOhNeK0+0HdqXlAp95eMLYe7NnuDylFK6kKvf9PMkvNxWX8lo0zUiGkXZr+iB9OLKJXYBIVO4RM8e6uZsOo6hkfcdvRh9WoFugT1Pmt6p+i6OmQ5gzrKlE025/yg34m3b+RN47Pnc8lsFRR3a3o3vHCnT6Szh5lG8hsmsWNOmlWH0EYbfF4CdS2J12sn3VfqIcilDaj+UEYGqXb6hgw="