services:
  - docker
branches:
  only:
    - master
install:
  - docker build --target test --tag todo-app:test .
script:
  - docker run todo-app:test tests
  - docker run -e DB_CONNECTION_STRING todo-app:test tests_e2e
after_success:
  - echo $DOCKER_PASSWORD | docker login --username chengjoanna1729 --password-stdin
  - docker build --target production --tag chengjoanna1729/todo-app:latest .
  - docker tag chengjoanna1729/todo-app:latest chengjoanna1729/todo-app:$TRAVIS_COMMIT
  - docker push chengjoanna1729/todo-app:$TRAVIS_COMMIT
before_deploy:
  - docker push chengjoanna1729/todo-app:latest
  - docker pull chengjoanna1729/todo-app
deploy:
  provider: script
  script: curl -dH -X POST "$WEBHOOK"
  on:
    branch: exercise-11
env:
  global:
  - secure: F2xfgjhsGpnzRHQIAkakCh7J9/PZTZV9AKhLDuPURmZlSBdZ+iR2wvyWHQ97Q9wO/UMmUxuJT/b4k4LkuHEZLGSKl6pzRgg+2Prhz/MTDvTYJYwIAdfSqws0U6TqDVVLnLNNzy3az/zFhDEfztHzbcy4dzPCfGtcA46ziZtbyl28/yzjR/wQQCrl4xecfHjae5R9FF7CF2A8e9kAspjurW/s+0erXaCD49BVUd4AxT1yswhshI2MPHE4+NNPn+s9oskjUXaUmPEgg3I9vGtS5rASoLozp57Leuola1rJRZxd0TVs5nOX3Jv+5EaDECJzjNq6PcXC/JbcmBt4wt3r0UmJrOs3t9VHiPhd4/kPIHFq7rNgPpvKhwBN/aqAaTC9Jh/58HZD99LtNXO9EJR6yHtlFI8AdbAuNsj6lFGtOGDv6dQyMYYigdMKoaK3zIh6Wm9L1YFboYbTcvP2Fc0HvoH9YeLQ63wqd5VuHT92gOgNSu6/biTczdzMk8qpDcgTH2db34dwCqxIf97rNOE75VQw7EBuU2gsUPbU2TNRHml1ExmFDGl9tAlxddFDm0FIsDzWbyA6BCoK4M+f5MF/Bgm6+YJyQZr0AZrKTcpvHHs6n+FLjlf6W7Mh+GBnY7rjWU2LxF9ibepEGE+PFnaNb4ILJXg7CZmcN0nqt8z0DwE=
  - COLLECTION_NAME=todos
  - secure: RnZmU0KF+Du828GtxhP4Y321zM7D665zrbUX7a/1YNdALCVONfDJZ4g4UjtWI/eE1AZ6hTHcsNHPb4RRgjOK4FXYKUP87xATPOzrCIzpIDqtLRXOl7onhDx8GXQrAjIuczt1prNmbcvBNOI/fgoXfXj5HiNP0svysaVxunWEC6f0+WU4WlIPbnqYolZFPlpGOq7jnTAXHiLqptnKit2fwn65M5hS9X2tvlshZbkeIykvoMonnopNALUH0sDN9Q8/Lt2f4c9pAtZwlM2KR3Uk2Hlp5h3auL7DyVNEOaFl24vYsz1bF836q5DqqZPsnbRdG8OpkBeE6QRhENCdHFmB5WLBC1xAwQHPSY+tq0iBxBWVu69La7xeVYge7dAUs3Qg7d5A4zQvKwlTBQM8Zig3Pw+b9hvdpqexi1G/Jzomvk9n+owJtBHMr4Srkw7xlCKsEELJPdbeX3ezApLGPvcGQw+TKisBLIRmg0CzmWoQrw97Hu+1Z49A3lKJSYkIWR/gFJVOmp8kKUDAOj3+ho8ET5WnlQM1ce5gW9X8oVEZgVOlOFsd358kayeuREEcDd80JDkaryfBRssdw2ea8kWAvpKK2cYKOa3x8P6v19ITjyhKJ1YIHgMESfQ/PC4nnQ2atcl9TtJs+yr7kHf00eom4ySvCCfe94ZsEUuAhIcmNB0=
  - secure: I2CgqZ/2P8b3bEWnEM/UJ+TYMZt36IAnKvrmDswLgENeZXDH5FeYZrUJTimQ8HaBIN/+WWUngMfVk52Wt4dl6nPkZI+9AB1DDKqYrxaKENnOAjz9zYQz0f1Wqqv15TmhKlsRe/RKCIREmVI9ATQjeb0xN0IhOi0maTSsHCP0L5Virza38mBSlAVPMUob4ESzKm14aXniCuc9riwxQbHnnJMXV0AMBatm93ljRyGsPJ+SDe7B8hGtO7sM82ZN5BR9naljLQAGskZUPY3IG3+6xANgLzQS6ELk9mwMBvzkKQgPIc+HH/IiHJaXiHFZVrA5i6UhnPKXRS8VMozOlr9B5Fvc5n6HsxVz2VaIVbZjJJn1YCjVDLR28CZ/G7iJcWxhdDzpqTVi8S/tGxNE0ZmTcoK4zBhoB1MOsZPxk+JyCxrjzYnM4cmgi3kkwg3/9QAJoy41BsBE6GcjLCNerYxsM5XBu9wzQmEcvvhPi0tX6ISz0hbygT27CLLQ/xe1cUJxKhLtWXztbDbbBKYFgU2u8eKs1p88lFPKu3REAeE7bfdab1w7oswiT9GTE+HFqCzlG0MjAfqhnIQedSoSebZg5skrhZlIxxGEcpwFpMohlFcaaY6PZRdwI+zt39v8j/w71AT8M04FCyMbrGJ62O0Swc+FsS3WtFSeo1KY70iraVk=