version: '3.8'
services:
    todo-app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - '5000:5000'
        env_file: .env
        volumes:
            - .:/src
        