version: '3.8'
services:
    todo-app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        ports:
            - '5000:8000'
        env_file: .env
        